/* Written by
 * Evan Lalopoulos <evan.lalopoulos.2017@my.bristol.ac.uk>
 * Harrison Boyns <hb17757.2017@my.bristol.ac.uk>
 * A project for Web Technologies
 * University of Bristol, May 2018
 * Copyright (C) - All Rights Reserved
 * Unauthorized copying of this file is strictly prohibited
 */
 
import React, { Component } from "react";
import { connect } from "react-redux";

import {
  Container,
  Row,
  Collapse,
  Navbar,
  NavbarToggler,
  NavbarBrand,
  Nav,
  NavItem,
  NavLink
} from "reactstrap";

class Header extends Component {
  constructor(props) {
    super(props);

    this.toggle = this.toggle.bind(this);
    this.state = {
      isOpen: true
    };
  }

  // Navbar toggle
  toggle() {
    this.setState({
      isOpen: !this.state.isOpen
    });
  }

  // differente navbar for logged in users
  renderNavbar() {
    switch(this.props.userAuth) {
      case null:
      return;
      case false:
      return (
        <Nav className="ml-auto" navbar>
          <NavItem>
            <NavLink href="/">Home</NavLink>
          </NavItem>
          <NavItem>
            <NavLink href="/search">Search</NavLink>
          </NavItem>
          <NavItem>
            <NavLink href="/login">Login</NavLink>
          </NavItem>
          <NavItem>
            <NavLink href="/register">Register</NavLink>
          </NavItem>
        </Nav>
      );
      default:
      return (
        <Nav className="ml-auto" navbar>
          <NavItem>
            <NavLink href="/search">Search</NavLink>
          </NavItem>
          <NavItem>
            <NavLink href="/editProfile">Edit profile</NavLink>
          </NavItem>
          <NavItem>
            <NavLink href="/messages">Messages</NavLink>
          </NavItem>
          <NavItem>
            <NavLink href="/api/logout">Logout</NavLink>
          </NavItem>
        </Nav>
      );
    }
  }

  render() {
    console.log(this.props.userAuth);
    return (
      <header>
        <Container>
          <Row>
            <Navbar color="light" light expand="md">
              <NavbarBrand href="/">
                <img class="logo" src="/assets/images/logo.svg" alt="opentutr logo" />
              </NavbarBrand>
              <NavbarToggler onClick={this.toggle} />
              <Collapse isOpen={this.state.isOpen} navbar>
                {this.renderNavbar()}
              </Collapse>
            </Navbar>
          </Row>
        </Container>
      </header>
    );
  }
}

function mapStateToProps(state) {
  // the userAuth property is generated by state.userAuth
  // see combined reducer
  return {userAuth: state.userAuth};
}

export default connect(mapStateToProps)(Header);
